### PR TITLE
Update to egui 0.20

### PR DESCRIPTION
**Pull request by kkngsm**
- update to egui 0.20
- replace `Stroke::none()` with `Stroke::None`

### CODE REVIEW

**Comment by kkngsm** [comment]
Now I am working on trunk support

**Review by setzer22 — APPROVED** [review]
Thanks! ~~Looks like this was an pretty clean upgrade :)~~ EDIT: See below :sweat_smile:

**Review by setzer22 — CHANGES_REQUESTED** [review]
Ooops, sorry about the hasty review. I have pulled the changes and it looks like the upgrade may take a bit more work than this. If you try running the examples and moving things around you'll see it's no longer working. You can't move nodes or alter their values.

This is probably related to this breaking [change in 0.20](https://github.com/emilk/egui/blob/master/CHANGELOG.md):
> :warning:  BREAKING: if you have overlapping interactive widgets, only the top widget (last added) will be interactive (https://github.com/emilk/egui/pull/2244).

I suspect how this is an issue, since the way we were doing background click detection conflicts with this new way of handling events in egui. Shouldn't be a difficult fix but unfortunately I don't have a lot of time to debug this right now.

**Comment by kkngsm** [comment]
I'm sorry...
I mistakenly thought it was a bug caused by trunk and was in the process of trying to figure out a fix.

It was an overall bug.

**Comment by setzer22** [comment]
No worries :slightly_smiling_face:

**Comment by kkngsm** [comment]
# Details
- [Fixed bug of interaction](https://github.com/setzer22/egui_node_graph/pull/79/commits/bd1de14504ce4e4a4d255fbc7b4718d5ac1fbe1f)
Changed node to be drawn by Area and Frame above it. This allows the interaction to work.

- [Fixed node display](https://github.com/setzer22/egui_node_graph/pull/79/commits/7c10d86e44ee1d7b0a17f0553a15f3705eaecca3)
Changed to draw from Frame information and removed body_bottom Shape.

**Comment by kkngsm** [comment]
[Support trunk](https://github.com/setzer22/egui_node_graph/pull/79/commits/619b8db42e7af451c9d6589059fb890c896d919b)
this commit includes favicon file etc.

**Comment by kkngsm** [comment]
Oh... sorry.
I can't frame out the node, so I need to fix it a bit more.

**Comment by setzer22** [comment]
Yeah, the problem with using `Area` to draw the nodes is that an area is made to always be inside the screen, but the node editor needs to allow panning nodes outside the view.

But it seems you're going in a pretty good direction. We may be able to solve #71 with these changes! :smile:

**Comment by setzer22** [comment]
I just realized there's also another problem with using an area: It would allow nodes to be drawn on top of any other area like Windows, but we typically don't want that. Egui doesn't expose a way to control the layer order of areas, and will "raise" whichever area was interacted to the top.

It wouldn't be so much the nodes being "inside" the node editor but floating "above" it like every other window. This might cause trouble in certain applications.
egui_node_graph_interaction_bug

**Comment by kkngsm** [comment]
I agree. It seems that using Area was not a good idea.

I'll give it some more thought. And, I feel that the other Frame and Trunk commits are useful and independent of egui0.20 and would be better split into a separate PR.

**Comment by ferid-akifzade** [comment]
Hi,

Is there any update about that?

**Comment by kkngsm** [comment]
No, it has not been corrected since then.

**Comment by setzer22** [comment]
@ferid-akifzade  I'm sorry, I haven't had time to debug this either :sweat_smile:. I've been a bit bugged by several of egui's limitations, so I am currently working on [a project that drops down to `epaint` and implements a different UI system on top](https://github.com/setzer22/guee). Whether this is going to be a project worth releasing or not, it's hard to tell at this time, but I have some initial results. Nothing too fancy, but hey! At least zoom is working there without my previous ugly hacks :smile:
new_guee

I'm still interested in updating this library, but since I am not currently using egui 0.20, it's a bit hard to find time to commit to this fix. This sounded like it should've been an easy fix, but when I tried it I realized it's not as easy as I thought

**Comment by ledyba** [comment]
FYI: egui v0.21 has been released: [egui - Rust](https://docs.rs/egui/latest/egui/)

I tried this PR with egui v 0.21, I can't compile....

```
error[E0053]: method `data_type_color` has an incompatible type for trait
  --> src\editor\synth\nodes.rs:56:62
   |
56 |   fn data_type_color(&self, _user_state: &mut GraphState) -> egui::Color32 {
   |                                                              ^^^^^^^^^^^^^
   |                                                              |
   |                                                              expected struct `ecolor::color32::Color32`, found struct `Color32`
   |                                                              help: change the output type to match the trait: `ecolor::color32::Color32`
   |
   = note: expected fn pointer `fn(&DataType, &mut GraphState) -> ecolor::color32::Color32`
              found fn pointer `fn(&DataType, &mut GraphState) -> Color32`
```

**Comment by kkngsm** [comment]
We already know that Area is inappropriate, so we removed the code using Area.

**Comment by kkngsm** [comment]
The current problem is that I need [`stopPropagation()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) in javascript, and I don't know how to do it!

Currently, responses are obtained in two places.
https://github.com/setzer22/egui_node_graph/blob/89186a6888dd824312b6ea9143106163990df764/egui_node_graph/src/editor_ui.rs#L167
https://github.com/setzer22/egui_node_graph/blob/89186a6888dd824312b6ea9143106163990df764/egui_node_graph/src/editor_ui.rs#L794-L798

However, with the update of egui's event system, this no longer works.

Perhaps window_response was a bad hack. For example, I expect that we can use the Response of the Frame used to draw the node in this PR.
https://github.com/setzer22/egui_node_graph/blob/89186a6888dd824312b6ea9143106163990df764/egui_node_graph/src/editor_ui.rs#L521-L580

But I've tried several patterns and they haven't worked.

**Comment by hakolao** [comment]
Thinking https://github.com/emilk/egui/issues/2947 and https://github.com/emilk/egui/issues/2471 are probably related. Debugged some:
```rust
        println!(
            "{:?} {:?}",
            window_response.drag_delta(),
            window_response.clicked_by(PointerButton::Primary)
        );
```
These always return 0.0, 0.0 and false.

One could probably hack around it

**Comment by setzer22** [comment]
Thank you all for the hard work, and sorry it took me a while to get back to this PR :)  It seems #85 supersedes this?

**Comment by kkngsm** [comment]
Sorry for not being involved in the discussion lately. I think it's so good！

**Pull request closed without merging**
