### PR TITLE
return disconnect responses before removal response

### PR DESCRIPTION
**Pull request by bpostlethwaite**
Currently egui_node_graph returns the node removal response before disconnection responses during node deletion. User code is likely to want to clean up connections before running any logic that handles node removal directly. This PR re-orders the responses so that disconnect responses are emitted before the removal response. This PR should be considered as introducing a breaking change, and one that isn't protected by types. As such it could lead to bugs in user code that depended on the old order. Still I think this is a more logical ordering so I am submitting this PR for consideration. Thank you.

### CODE REVIEW

**Comment by setzer22** [comment]
This makes sense. Thanks for the PR! :+1:

**Comment by setzer22** [comment]
> This PR should be considered as introducing a breaking change, and one that isn't protected by types.

That is correct, but the new `DeleteNodeFull` response is not yet published in any crates.io release (AFAIK), so this change only breaks users of the master branch. I think that's reasonable, and the new ordering makes more sense.

**Comment by setzer22** [comment]
This makes me thing we may want to document the order in which events are sent at some point, so that users can rely on it. 

An alternative would be to document the order as being explicitly unspecified, so that users are aware of it and sort them in their preferred way (if needed). But I'm not sure this is a good idea :thinking:

**Comment by bpostlethwaite** [comment]
awesome thanks, that removes some unnecessary cloning and munging of the responses on my end

**Pull request merged**
